### ISSUE TITLE
qcelemental does not build with Python 3.12

### ISSUE THREAD

**Issue by susilehtola** [MolSSI/QCElemental#313]
QCElemental does not build with Python 3.12, included in Fedora rawhide.

The error is
```
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -sP'
/builddir/build/BUILD/QCElemental-0.25.1/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "/builddir/build/BUILD/QCElemental-0.25.1/setup.py", line 27, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/QCElemental-0.25.1/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/QCElemental-0.25.1/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/QCElemental-0.25.1/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
error: Bad exit status from /var/tmp/rpm-tmp.1ZzK1S (%build)
    Bad exit status from /var/tmp/rpm-tmp.1ZzK1S (%build)
RPM build errors:
Child return code was: 1
```

You need to update the bundled versioneer.

**Comment by bennybp** [comment]
Looks like the `versioneer.py` file will need to be updated:

https://github.com/python-versioneer/python-versioneer/issues/200

**Comment by loriab** [comment]
versioneer has been removed in current master, so this issue should resolve as soon as I've minted v0.26.0. In case anyone needs to patch an earlier version, here's a likely solution Ben found.

```
     setup_cfg = os.path.join(root, "setup.cfg")
-    parser = configparser.SafeConfigParser()
+    parser = configparser.ConfigParser()
     with open(setup_cfg, "r") as f:
-        parser.readfp(f)
+        parser.read_file(f)
     VCS = parser.get("versioneer", "VCS")  # mandatory
```

**Comment by loriab** [comment]
v0.26.0 w/o versioneer should close this. Please repoen if more needed for py312.
